### ISSUE TITLE
About the header information

### ISSUE THREAD

**Issue by LuZWCHA** [WonderLandxD/sdpc-for-python#1]
How can I get the pixel size of a slide. No clear description in the sdpc_structure file. THANKS.

**Comment by WonderLandxD** [comment]
> 

You can use `wsi.level_dimensions` to get the pixel size in each level.
![1711672149563_ pic](https://user-images.githubusercontent.com/100405945/209677207-67edba2f-a6e7-41ce-9a21-1a616749df1a.jpg)
