### ISSUE TITLE
sdpc to svs

### ISSUE THREAD

**Issue by shenxiaochenn** [WonderLandxD/sdpc-for-python#4]
Hi, I would like to ask you how to convert wsi in "sdpc" format to the common svs format. In fact, most of the wsi data is in svs format.

**Comment by WonderLandxD** [comment]
Thank you for your interest.
According to our known research content, the storage space of WSI in “sdpc” format is smaller, and the processing using sdpc library is almost the same as using the Openslide library that supports the “svs” format, so there is no need to convert sdpc to svs. If you must do this, I can provide you with a software to convert them, please leave your contact information.

**Comment by mimimay-cpu** [comment]
Hi, would you share with the software to convert sdpc to svs,thanks

**Comment by WonderLandxD** [comment]
> Hi, would you share with the software to convert sdpc to svs,thanks

please see the issue #8

**Comment by 200109110057Wjy** [comment]
> Hi, would you share with the software to convert sdpc to svs,thanks

**Comment by wangshuo95279527** [comment]
Hi, would you share with the software to convert sdpc to svs,thanks。It is very important for me.
