### ISSUE TITLE
Implementation of get_best_level_for_downsample()

### ISSUE THREAD

**Issue by MrPeterJin** [WonderLandxD/sdpc-for-python#5]
Hi,

Thanks for your wonderful work. However, Is there a possibility for you to implement get_best_level_for_downsample() like the Openslide package offers?

Reference: https://openslide.org/api/python/#openslide.OpenSlide.get_best_level_for_downsample

**Comment by WonderLandxD** [comment]
Hello, thank you for your feedback! Since our team does not currently have a need for this function, we have not considered adding it at this time when making the library public. However, in the future, when the appropriate time comes, we will consider incorporating some common functions of Openslide. Please stay tuned for updates!

**Comment by MrPeterJin** [comment]
Thanks for your reply. Would you mind if I create a Pull Request if I implement this function?

**Comment by WonderLandxD** [comment]
Certainly! Thank you very much for your help. Your contribution is valuable to the community.

**Comment by MrPeterJin** [comment]
> Certainly! Thank you very much for your help. Your contribution is valuable to the community.

Please check #6.

**Comment by MrPeterJin** [comment]
> Certainly! Thank you very much for your help. Your contribution is valuable to the community.

Hi, is there any problem with this PR? Since the page is in inactivity state for 2 days.

**Comment by WonderLandxD** [comment]
> > Certainly! Thank you very much for your help. Your contribution is valuable to the community.
> 
> Hi, is there any problem with this PR? Since the page is in inactivity state for 2 days.

Sorry for the delayed response! Our team is quite busy these days, you can manually modify the local environment to execute the function first, we expect to upload a new version next week. Thank you for your positive feedback!
