### ISSUE TITLE
ValueError: NULL pointer access

### ISSUE THREAD

**Issue by zero19970** [WonderLandxD/sdpc-for-python#7]
File /cache/lch/anaconda3/lib/python3.8/site-packages/sdpc/Sdpc.py:29, in Sdpc.__init__(self, sdpcPath)
     27 def __init__(self, sdpcPath):
     28     print(sdpcPath)
---> 29     self.sdpc = self.readSdpc(sdpcPath)
     30     self.level_count = self.getLevelCount()
     31     self.level_downsample = self.getLevelDownsamples()

File /cache/lch/anaconda3/lib/python3.8/site-packages/sdpc/Sdpc.py:42, in Sdpc.readSdpc(self, fileName)
     39 def readSdpc(self, fileName):
     41     sdpc = so.SqOpenSdpc(c_char_p(bytes(fileName, 'gbk')))
---> 42     sdpc.contents.fileName = bytes(fileName, 'gbk')
     44     return sdpc

ValueError: NULL pointer access

**Comment by WonderLandxD** [comment]
Are you sure the WSI format you input is in sdpc?

**Comment by zero19970** [comment]
Yes
