### ISSUE TITLE
convert sdpc to svs

### ISSUE THREAD

**Issue by lu-kyo** [WonderLandxD/sdpc-for-python#8]
Hi, could you please help me deal with the problem? I have problem in converting "sdpc" format to "svs" format. I have seen the issues before, someone raised the same problem as me, and you selflessly provided a software to convert them. I wonder if it is possible that you could send the software to me either. MY EMAIL ADDRESS is yulushi0909@163.com. Thanks for helping.
Best wishes
Yulu

**Comment by lu-kyo** [comment]
thanks again ， I have converted it from the app.

---- Replied Message ----
| From | Jerry Jiawen ***@***.***> |
| Date | 11/10/2023 22:42 |
| To | WonderLandxD/sdpc-for-python ***@***.***> |
| Cc | lu-kyo ***@***.***>,
Author ***@***.***> |
| Subject | Re: [WonderLandxD/sdpc-for-python] convert sdpc to svs (Issue #8) |

Hi,
Due to company license restrictions, perhaps you can contact the unit or institution from which you obtained the data and they can help you.

**Comment by ymir-twice** [comment]
> thanks again ， I have converted it from the app.
> […](#)
> ---- Replied Message ---- | From | Jerry Jiawen ***@***.***> | | Date | 11/10/2023 22:42 | | To | WonderLandxD/sdpc-for-python ***@***.***> | | Cc | lu-kyo ***@***.***>, Author ***@***.***> | | Subject | Re: [WonderLandxD/sdpc-for-python] convert sdpc to svs (Issue #8) | Hi, Due to company license restrictions, perhaps you can contact the unit or institution from which you obtained the data and they can help you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Hi, could tell me which app did you use to convert wsi in sdpc format to wsi in svs format? It's important for me.

**Comment by 200109110057Wjy** [comment]
> Could tell me which app did you use to convert wsi in sdpc format to wsi in svs format too?  thank u very much

**Comment by nicedoctor123** [comment]
Hi, could tell me which app did you use to convert wsi in sdpc format to wsi in svs format? It's important for me.I wonder if it is possible that you could send the software to me either. MY EMAIL ADDRESS is [**xiakun@stu.xmu.edu.cn**]. Thanks for helping.
Best wishes

**Comment by wangshuo95279527** [comment]
Hi, could tell me which app did you use to convert wsi in sdpc format to wsi in svs format? It's important for me

**Comment by TanPiaoLing** [comment]
Hello, I would like to ask if it is possible to use scripts or software to batch convert SDPC format images to TIFF or svs. If you could tell me, it would be the greatest help to us! Email: 2274356307@qq.com

**Comment by wangshuo95279527** [comment]
深圳生强科技官网那个阅片软件，下载之后，在格式转化那里右键有个转化为svs可以实现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WonderLandxD/opensdpc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年6月23日(星期一) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WonderLandxD/opensdpc] convert sdpc to svs (Issue #8)



TanPiaoLing left a comment (WonderLandxD/opensdpc#8)
 
Hello, I would like to ask if it is possible to use scripts or software to batch convert SDPC format images to TIFF or svs. If you could tell me, it would be the greatest help to us! Email: ***@***.***
